"definitions" : {
	"user": {
		"type": "object",
		"properties": {
			"username": {
				"type": "string"
			},
			"password": {
				"type": "string"
			},
			"email": {
				"type": "string"
			}
		}
	},
	"event": {
		"type": "object",
		"properties": {
			"title": {
				"type": "string"
			},
			"status": {
				"type": "string"
			},
			"date": {
				"type": "string"
			},
			"description": {
				"type": "string"
			}
		}
	}
}